import XCTest
@testable import Sierra

extension Trip {
    static func makeTest(
        id: UUID = UUID(),
        taskId: String = "TRP-20260101-0001",
        driverId: String? = nil,
        vehicleId: String? = nil,
        createdByAdminId: String = "F0000000-0000-0000-0000-000000000001",
        origin: String = "Origin",
        destination: String = "Destination",
        originLatitude: Double? = nil,
        originLongitude: Double? = nil,
        destinationLatitude: Double? = nil,
        destinationLongitude: Double? = nil,
        routePolyline: String? = nil,
        routeStops: [RouteStop]? = nil,
        deliveryInstructions: String = "",
        scheduledDate: Date = Date(),
        scheduledEndDate: Date? = nil,
        actualStartDate: Date? = nil,
        actualEndDate: Date? = nil,
        startMileage: Double? = nil,
        endMileage: Double? = nil,
        notes: String = "",
        status: TripStatus = .scheduled,
        priority: TripPriority = .normal,
        proofOfDeliveryId: UUID? = nil,
        preInspectionId: UUID? = nil,
        postInspectionId: UUID? = nil,
        acceptedAt: Date? = nil,
        acceptanceDeadline: Date? = nil,
        rejectedReason: String? = nil,
        driverRating: Int? = nil,
        driverRatingNote: String? = nil,
        ratedById: UUID? = nil,
        ratedAt: Date? = nil,
        createdAt: Date = Date(),
        updatedAt: Date = Date()
    ) -> Trip {
        Trip(
            id: id,
            taskId: taskId,
            driverId: driverId,
            vehicleId: vehicleId,
            createdByAdminId: createdByAdminId,
            origin: origin,
            destination: destination,
            originLatitude: originLatitude,
            originLongitude: originLongitude,
            destinationLatitude: destinationLatitude,
            destinationLongitude: destinationLongitude,
            routePolyline: routePolyline,
            routeStops: routeStops,
            deliveryInstructions: deliveryInstructions,
            scheduledDate: scheduledDate,
            scheduledEndDate: scheduledEndDate,
            actualStartDate: actualStartDate,
            actualEndDate: actualEndDate,
            startMileage: startMileage,
            endMileage: endMileage,
            notes: notes,
            status: status,
            priority: priority,
            proofOfDeliveryId: proofOfDeliveryId,
            preInspectionId: preInspectionId,
            postInspectionId: postInspectionId,
            acceptedAt: acceptedAt,
            acceptanceDeadline: acceptanceDeadline,
            rejectedReason: rejectedReason,
            driverRating: driverRating,
            driverRatingNote: driverRatingNote,
            ratedById: ratedById,
            ratedAt: ratedAt,
            createdAt: createdAt,
            updatedAt: updatedAt
        )
    }
}
